-- phpMyAdmin SQL Dump
-- version 4.2.10
-- http://www.phpmyadmin.net
--
-- Host: localhost:8889
-- Czas generowania: 10 Mar 2016, 11:34
-- Wersja serwera: 5.5.38
-- Wersja PHP: 5.6.2

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

--
-- Baza danych: `extra-opd`
--

-- --------------------------------------------------------

--
-- Struktura tabeli dla tabeli `content`
--

CREATE TABLE `content` (
`id` int(11) NOT NULL,
  `time_add` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `title` varchar(255) COLLATE utf8_bin NOT NULL,
  `description` varchar(999) COLLATE utf8_bin NOT NULL,
  `year` varchar(255) COLLATE utf8_bin NOT NULL,
  `img` varchar(255) COLLATE utf8_bin NOT NULL,
  `yt_link` varchar(255) COLLATE utf8_bin NOT NULL,
  `views` int(255) NOT NULL
) ENGINE=InnoDB AUTO_INCREMENT=42 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

--
-- Zrzut danych tabeli `content`
--

INSERT INTO `content` (`id`, `time_add`, `title`, `description`, `year`, `img`, `yt_link`, `views`) VALUES
(1, '2016-02-25 10:18:21', 'The Godfather', 'Widely regarded as one of the greatest films of all time, this mob drama, based on Mario Puzo''s novel of the same name, focuses on the powerful Italian-American crime family of Don Vito Corleone (Marlon Brando). When the don''s youngest son, Michael (Al Pacino), reluctantly joins the Mafia, he becomes involved in the inevitable cycle of violence and betrayal. Although Michael tries to maintain a normal relationship with his wife, Kay (Diane Keaton), he is drawn deeper into the family business.', '1972', 'godfather.jpg', '5DO-nDW43Ik', 2360),
(2, '2016-02-25 20:08:21', 'The Avengers: Age of Ultron', 'When Tony Stark (Robert Downey Jr.) jump-starts a dormant peacekeeping program, things go terribly awry, forcing him, Thor (Chris Hemsworth), the Incredible Hulk (Mark Ruffalo) and the rest of the Avengers to reassemble. As the fate of Earth hangs in the balance, the team is put to the ultimate test as they battle Ultron, a technological terror hell-bent on human extinction. Along the way, they encounter two mysterious and powerful newcomers, Pietro and Wanda Maximoff.', '2015', 'avengers2.jpg', 'rD8lWtcgeyg', 76),
(3, '2016-02-25 20:11:54', 'Terminator 2: Judgment Day', 'In this sequel set eleven years after "The Terminator," young John Connor (Edward Furlong), the key to civilization''s victory over a future robot uprising, is the target of the shape-shifting T-1000 (Robert Patrick), a Terminator sent from the future to kill him. Another Terminator, the revamped T-800 (Arnold Schwarzenegger), has been sent back to protect the boy. As John and his mother (Linda Hamilton) go on the run with the T-800, the boy forms an unexpected bond with the robot.', '1991', 'terminator2.jpg', 'F1os6UU6jhU', 212),
(4, '2016-02-25 20:13:14', 'Foxcatcher', 'When wealthy John du Pont (Steve Carell) invites Olympic wrestler Mark Schultz (Channing Tatum) to move to his estate and help form a wrestling team for the 1988 Olympics, Mark sees a way to step out of the shadow of his charismatic brother, Dave (Mark Ruffalo). However, du Pont begins to lead Mark down a dark road, causing the athlete''s self-esteem to slip. Meanwhile, du Pont becomes fixated on bringing Dave into the fold, eventually propelling all three toward an unforeseen tragedy.', '2014', 'foxcatcher.jpg', '8361stZ8n0w', 1894),
(5, '2016-02-25 20:18:45', 'Batman Begins', 'A young Bruce Wayne (Christian Bale) travels to the Far East, where he''s trained in the martial arts by Henri Ducard (Liam Neeson), a member of the mysterious League of Shadows. When Ducard reveals the League''s true purpose -- the complete destruction of Gotham City -- Wayne returns to Gotham intent on cleaning up the city without resorting to murder. With the help of Alfred (Michael Caine), his loyal butler, and Lucius Fox (Morgan Freeman), a tech expert at Wayne Enterprises, Batman is born.', '2005', 'batman_begins.jpg', 'neY2xVmOfUM', 479),
(6, '2016-02-25 20:35:33', 'Titanic', 'James Cameron''s "Titanic" is an epic, action-packed romance set against the ill-fated maiden voyage of the R.M.S. Titanic; the pride and joy of the White Star Line and, at the time, the largest moving object ever built. She was the most luxurious liner of her era -- the "ship of dreams" -- which ultimately carried over 1,500 people to their death in the ice cold waters of the North Atlantic in the early hours of April 15, 1912.', '1997', 'titanic.jpg', 'zCy5WQ9S4c0', 91),
(7, '2016-02-25 22:20:18', 'Forrest Gump', 'Slow-witted Forrest Gump (Tom Hanks) has never thought of himself as disadvantaged, and thanks to his supportive mother (Sally Field), he leads anything but a restricted life. Whether dominating on the gridiron as a college football star, fighting in Vietnam or captaining a shrimp boat, Forrest inspires people with his childlike optimism. But one person Forrest cares about most may be the most difficult to save -- his childhood love, the sweet but troubled Jenny (Robin Wright).', '1994', 'forrest_gump.jpg', 'bLvqoHBptjg', 887),
(8, '2016-02-25 22:22:07', 'Avatar', 'On the lush alien world of Pandora live the Na''vi, beings who appear primitive but are highly evolved. Because the planet''s environment is poisonous, human/Na''vi hybrids, called Avatars, must link to human minds to allow for free movement on Pandora. Jake Sully (Sam Worthington), a paralyzed former Marine, becomes mobile again through one such Avatar and falls in love with a Na''vi woman (Zoe Saldana). As a bond with her grows, he is drawn into a battle for the survival of her world.', '2009', 'avatar.jpg', '5PSNL1qE6VY', 454),
(9, '2016-03-02 20:32:53', 'Intouchables', 'An unlikely friendship develops between a wealthy quadriplegic (François Cluzet) and his caretaker (Omar Sy), just released from prison.', '2011', 'intouchables.jpg', '34WIbmXkewU', 212),
(10, '2016-03-02 20:34:56', 'The Godfather: Part II', 'The compelling sequel to "The Godfather," contrasting the life of Corleone father and son. Traces the problems of Michael Corleone (Al Pacino) in 1958 and that of a young immigrant Vito Corleone (Robert De Niro) in 1917''s Hell''s Kitchen. Michael survives many misfortunes and Vito is introduced to a life of crime.', '1974', 'godfather-part2.jpg', '9O1Iy9od7-A', 293),
(11, '2016-03-02 20:36:50', 'The Godfather: Part III', 'As Michael Corleone (Al Pacino) ages, he finds that being the head of the Corleone crime family isn''t getting any easier. He wants his family out of the Mafia, but the mob kingpin (Eli Wallach) isn''t eager to let one of the most powerful and wealthy families go legit. Making matters even worse is Michael''s nephew, Vincent (Andy Garcia). Not only does Vincent want a piece of the Corleone family''s criminal empire, but he also wants Michael''s daughter, Mary (Sofia Coppola).', '1990', 'godfather-part3.jpg', 'MMZW74OhB-s', 765),
(12, '2016-03-02 20:38:37', 'Fight Club', 'A depressed man (Edward Norton) suffering from insomnia meets a strange soap salesman named Tyler Durden (Brad Pitt) and soon finds himself living in his squalid house after his perfect apartment is destroyed. The two bored men form an underground club with strict rules and fight other men who are fed up with their mundane lives. Their perfect partnership frays when Marla (Helena Bonham Carter), a fellow support group crasher, attracts Tyler''s attention.', '1999', 'fightclub.jpg', 'SUXWAEX2jlg', 456),
(13, '2016-03-02 20:45:35', 'Inception', 'Dom Cobb (Leonardo DiCaprio) is a thief with the rare ability to enter people''s dreams and steal their secrets from their subconscious. His skill has made him a hot commodity in the world of corporate espionage but has also cost him everything he loves. Cobb gets a chance at redemption when he is offered a seemingly impossible task: Plant an idea in someone''s mind. If he succeeds, it will be the perfect crime, but a dangerous enemy anticipates Cobb''s every move.', '2010', 'inception.jpg', '8hP9D6kZseM', 987),
(14, '2016-03-04 16:29:29', 'The Silence of the Lambs', 'Jodie Foster stars as Clarice Starling, a top student at the FBI''s training academy. Jack Crawford (Scott Glenn) wants Clarice to interview Dr. Hannibal Lecter (Anthony Hopkins), a brilliant psychiatrist who is also a violent psychopath, serving life behind bars for various acts of murder and cannibalism. Crawford believes that Lecter may have insight into a case and that Starling, as an attractive young woman, may be just the bait to draw him out.', '1991', 'silence_of_the_lambs.jpg', 'W6Mm8Sbe__o', 2340),
(15, '2016-03-04 16:30:50', 'The Pianist', 'In this adaptation of the autobiography "The Pianist: The Extraordinary True Story of One Man''s Survival in Warsaw, 1939-1945," Wladyslaw Szpilman (Adrien Brody), a Polish Jewish radio station pianist, sees Warsaw change gradually as World War II begins. Szpilman is forced into the Warsaw Ghetto, but is later separated from his family during Operation Reinhard. From this time until the concentration camp prisoners are released, Szpilman hides in various locations among the ruins of Warsaw.', '2002', '28359-b-the-pianist.jpg', 'u_jE7-6Uv7E', 345),
(16, '2016-03-04 16:32:48', 'Saving Private Ryan', 'Captain John Miller (Tom Hanks) takes his men behind enemy lines to find Private James Ryan, whose three brothers have been killed in combat. Surrounded by the brutal realties of war, while searching for Ryan, each man embarks upon a personal journey and discovers their own strength to triumph over an uncertain future with honor, decency and courage.', '1998', 'SavingPrivateRyan.jpg', 'vwAxi4A2YcY', 68),
(17, '2016-03-04 16:33:53', 'Gladiator', 'Commodus (Joaquin Phoenix) takes power and strips rank from Maximus (Russell Crowe), one of the favored generals of his predecessor and father, Emperor Marcus Aurelius, the great stoical philosopher. Maximus is then relegated to fighting to the death in the gladiator arenas.', '2000', 'Gladiator.jpg', 'owK1qxDselE', 5677),
(18, '2016-03-04 16:35:28', 'The Prestige', 'An illusion gone horribly wrong pits two 19th-century magicians, Alfred Borden (Christian Bale) and Rupert Angier (Hugh Jackman), against each other in a bitter battle for supremacy. Terrible consequences loom when the pair escalate their feud, each seeking not just to outwit -- but to destroy -- the other man.', '2006', 'ThePrestige.jpg', '9n2B5WW4SKk', 568),
(19, '2016-03-04 16:51:19', 'Dead Poets Society', 'A new English teacher, John Keating (Robin Williams), is introduced to an all-boys preparatory school that is known for its ancient traditions and high standards. He uses unorthodox methods to reach out to his students, who face enormous pressures from their parents and the school. With Keating''s help, students Neil Perry (Robert Sean Leonard), Todd Anderson (Ethan Hawke) and others learn to break out of their shells, pursue their dreams and seize the day.', '1989', 'deadpoetssociety.jpg', '4lj185DaZ_o', 239),
(20, '2016-03-04 16:55:00', 'The Dark Knight', 'With the help of allies Lt. Jim Gordon (Gary Oldman) and DA Harvey Dent (Aaron Eckhart), Batman (Christian Bale) has been able to keep a tight lid on crime in Gotham City. But when a vile young criminal calling himself the Joker (Heath Ledger) suddenly throws the town into chaos, the caped Crusader begins to tread a fine line between heroism and vigilantism.', '2008', 'TheDarkKnight.jpg', 'EXeTwQWrcwY', 444),
(21, '2016-03-09 04:26:14', 'Seven Pounds', 'A life-shattering secret torments Ben Thomas (Will Smith). In order to find redemption, he sets out to change the lives of seven strangers. Over the course of his journey, he meets and falls in love with a cardiac patient named Emily (Rosario Dawson), and in so doing, complicates his mission.', '2008', 'SevenPounds.jpg', 'vDohP0piYhA', 965),
(22, '2016-03-09 04:39:02', 'Interstellar', 'In Earth''s future, a global crop blight and second Dust Bowl are slowly rendering the planet uninhabitable. Professor Brand (Michael Caine), a brilliant NASA physicist, is working on plans to save mankind by transporting Earth''s population to a new home via a wormhole. But first, Brand must send former NASA pilot Cooper (Matthew McConaughey) and a team of researchers through the wormhole and across the galaxy to find out which of three planets could be mankind''s new home.', '2014', 'Interstellar.jpg', 'zSWdZVtXT7E', 812),
(23, '2016-03-09 04:40:22', 'The Martian', 'When astronauts blast off from the planet Mars, they leave behind Mark Watney (Matt Damon), presumed dead after a fierce storm. With only a meager amount of supplies, the stranded visitor must utilize his wits and spirit to find a way to survive on the hostile planet. Meanwhile, back on Earth, members of NASA and a team of international scientists work tirelessly to bring him home, while his crew mates hatch their own plan for a daring rescue mission.', '2015', 'TheMartian.jpg', 'ej3ioOneTy8', 633),
(24, '2016-03-09 04:41:38', 'Catch Me If You Can', 'Frank Abagnale, Jr. (Leonardo DiCaprio) worked as a doctor, a lawyer, and as a co-pilot for a major airline -- all before his 18th birthday. A master of deception, he was also a brilliant forger, whose skill gave him his first real claim to fame: At the age of 17, Frank Abagnale, Jr. became the most successful bank robber in the history of the U.S. FBI Agent Carl Hanratty (Tom Hanks) makes it his prime mission to capture Frank and bring him to justice, but Frank is always one step ahead of him.', '2002', 'CatchMeIfYouCan.jpg', '71rDQ7z4eFg', 52),
(25, '2016-03-09 04:42:57', 'The Illusionist', 'A master magician named Eisenheim (Edward Norton) vies with Crown Prince Leopold (Rufus Sewell) of Vienna for the hand of noblewoman Sophie (Jessica Biel), the girl he once loved. He brings his considerable powers to bear on the prince, as she is about to be named royal fiancee. However, a police inspector named Uhl (Paul Giamatti) tries to warn Eisenheim that he is playing a very dangerous game.', '2006', 'TheIllusionist.jpg', 'i0xO64icGSY', 773),
(26, '2016-03-09 08:55:05', 'Rambo', 'Having long-since abandoned his life as a lethal soldier, John Rambo (Sylvester Stallone) lives a solitary life near the Thai border. Two weeks after guiding a missionary (Julie Benz) and her comrades into Burma, he gets an urgent call for help. The missionaries have not returned and although he is reluctant to embrace violence again, Rambo sets out to rescue the captives from the Burmese army.', '2008', 'rambo.jpg', '2CRjdwRYQbU', 346),
(27, '2016-03-09 08:57:37', 'Mr. Bean''s Holiday', 'When London''s wet weather becomes too much to bear, pratfall-prone Mr. Bean (Rowan Atkinson) heads to the French Riviera for some fun in the sun. As usual, his plans do not go smoothly, and he is mistaken for both a kidnapper and an award-winning filmmaker when he arrives with a Romanian director''s son and an aspiring actress in tow.', '2007', 'mrbean.jpg', 'hSxLUd8aly4', 790),
(28, '2016-03-09 08:59:39', 'Rocky', 'Rocky Balboa (Sylvester Stallone), a small-time boxer from working-class Philadelphia, is arbitrarily chosen to take on the reigning world heavyweight champion, Apollo Creed (Carl Weathers), when the undefeated fighter''s scheduled opponent is injured. While training with feisty former bantamweight contender Mickey Goldmill (Burgess Meredith), Rocky tentatively begins a relationship with Adrian (Talia Shire), the wallflower sister of his meat-packer pal Paulie (Burt Young).', '1976', 'rocky.jpg', '7RYpJAUMo2M', 6906),
(29, '2016-03-09 09:04:53', 'Back to the Future', 'In this 1980s sci-fi classic, small-town California teen Marty McFly (Michael J. Fox) is thrown back into the ''50s when an experiment by his eccentric scientist friend Doc Brown (Christopher Lloyd) goes awry. Traveling through time in a modified DeLorean car, Marty encounters young versions of his parents (Crispin Glover, Lea Thompson), and must make sure that they fall in love or he''ll cease to exist. Even more dauntingly, Marty has to return to his own time and save the life of Doc Brown.', '1985', 'backto.jpg', 'qvsgGtivCgs', 2468),
(30, '2016-03-09 09:06:53', 'Star Wars: The Force Awakens', 'Thirty years after the defeat of the Galactic Empire, the galaxy faces a new threat from the evil Kylo Ren (Adam Driver) and the First Order. When a defector named Finn crash-lands on a desert planet, he meets Rey (Daisy Ridley), a tough scavenger whose droid contains a top-secret map. Together, the young duo joins forces with Han Solo (Harrison Ford) to make sure the Resistance receives the intelligence concerning the whereabouts of Luke Skywalker (Mark Hamill), the last of the Jedi Knights.', '2015', 'starwars.jpg', 'sGbxmsDFVnE', 2121),
(31, '2016-03-09 09:11:43', 'The Fast and the Furious', 'A fierce and frenzied look at rival Los Angeles street teams who use street racing as a means of establishing power. Walker stars as a rookie cop who goes undercover, posing as a racing team member, in order to investigate a jewelry heist. Managing to integrate himself with the team''s leaders at first, he finds himself in jeopardy when the other members being to suspect an imposter within their ranks, setting the stage for an exciting, climactic showdown.', '2001', 'fastandsrs.jpg', '2TAOizOnNPo', 872),
(32, '2016-03-09 09:13:05', 'The Amazing Spider-Man', 'Abandoned by his parents and raised by an aunt and uncle, teenager Peter Parker (Andrew Garfield), AKA Spider-Man, is trying to sort out who he is and exactly what his feelings are for his first crush, Gwen Stacy (Emma Stone). When Peter finds a mysterious briefcase that was his father''s, he pursues a quest to solve his parents'' disappearance. His search takes him to Oscorp and the lab of Dr. Curt Connors (Rhys Ifans), setting him on a collision course with Connors'' alter ego, the Lizard.', '2012', 'spiderman.jpg', 'oX9ZT3RbYE4', 1257),
(33, '2016-03-09 09:15:12', 'Deadpool', 'Wade Wilson (Ryan Reynolds) is a former Special Forces operative who now works as a mercenary. His world comes crashing down when evil scientist Ajax (Ed Skrein) tortures, disfigures and transforms him into Deadpool. The rogue experiment leaves Deadpool with accelerated healing powers and a twisted sense of humor. With help from mutant allies Colossus and Negasonic Teenage Warhead (Brianna Hildebrand), Deadpool uses his new skills to hunt down the man who nearly destroyed his life.', '2016', 'deadpool.jpg', '9vN6DHB6bJc', 4447),
(34, '2016-03-09 09:22:26', 'Bad Boys II', 'The drug ecstasy is flowing into Miami, and the police want it stopped. Police Detective Marcus Burnett (Martin Lawrence) and his partner, Mike Lowrey (Will Smith), are just the men to do it. They track the drugs to a Cuban smuggler, Johnny Tapia (Jordi Mollà), who is also involved in a bloody war with Russian and Haitian mobsters. If that isn''t bad enough, there''s tension between the two cops because Lowrey is romantically involved with Burnett''s sister, Syd (Gabrielle Union).', '2003', 'badboys.jpg', 'AURhd5TCG6U', 243),
(35, '2016-03-09 09:24:39', 'The Matrix', 'Neo (Keanu Reeves) believes that Morpheus (Laurence Fishburne), an elusive figure considered to be the most dangerous man alive, can answer his question -- What is the Matrix? Neo is contacted by Trinity (Carrie-Anne Moss), a beautiful stranger who leads him into an underworld where he meets Morpheus. They fight a brutal battle for their lives against a cadre of viciously intelligent secret agents. It is a truth that could cost Neo something more precious than his life.', '1999', 'matrix.jpg', 'm8e-FF8MsqU', 4893),
(36, '2016-03-10 10:27:32', 'Rush Hour 2', 'After an explosion at the US Embassy in Hong Kong kills two customs agents investigating currency smuggling, Inspector Lee (Jackie Chan) and James Carter (Chris Tucker) search for the mastermind. Ricky Tan (John Lone), head of the Fu-Cang-Long Triad, sends out his minions to insure that Carter and Lee don''t solve the case.', '2001', 'rushhour2.jpg', 'SCTzYY95Aw4', 302),
(37, '2016-03-10 10:27:32', 'Rush Hour 3', 'East meets West again when the assassination of Ambassador Han leads to the reunion of Lee (Jackie Chan) and Carter (Chris Tucker). In Paris, the pair must stay one step ahead of Chinese gangsters, and Lee''s childhood friend (Hiroyuki Sanada), as they track down an envelope containing the identity of a powerful crime lord.', '2007', 'rushhour3.jpg', 'FRDRWXfQyJE', 591),
(38, '2016-03-10 10:27:32', 'Mr. Hulot''s Holiday', 'When the ever-hapless Monsieur Hulot (Jacques Tati) decides to vacation at a beautiful seaside resort, rest and relaxation don''t last long, given the gangly gent''s penchant for ridiculous antics. While simply out to enjoy himself, the well-meaning Hulot inevitably stumbles into numerous misadventures, including an utterly disastrous attempt at playing tennis, as he encounters fellow French vacationers from various social classes, as well as foreign tourists.', '1953', 'lesvacances.jpg', '92Cm8gl7Ls', 284),
(39, '2016-03-10 10:27:32', 'Transformers', 'The fate of humanity is at stake when two races of robots, the good Autobots and the villainous Decepticons, bring their war to Earth. The robots have the ability to change into different mechanical objects as they seek the key to ultimate power. Only a human youth, Sam Witwicky (Shia LaBeouf) can save the world from total destruction.', '2007', 'transformers.jpg', 'gAjgXlvVexI', 1342),
(40, '2016-03-10 10:27:32', 'The Green Mile', 'Paul Edgecomb (Tom Hanks) walked the mile with a variety of cons. He had never encountered someone like John Coffey (Michael Clarke Duncan), a massive black man convicted of brutally killing a pair of young sisters. Coffey had the size and strength to kill anyone, but not the demeanor. Beyond his simple, naive nature and a deathly fear of the dark, Coffey seemed to possess a prodigious, supernatural gift. Paul began to question whether Coffey was truly guilty of murdering the two girls.', '1999', 'greenmile.png', 'Ki4haFrqSrw', 3222),
(41, '2016-03-10 10:27:32', 'The 39 Steps', 'While on vacation in London, Canadian Richard Hannay (Robert Donat) becomes embroiled in an international spy ring related to the mysterious "39 steps." Then he meets agent Annabella Smith (Lucie Mannheim), who is soon killed in his apartment. He must elude the police, who are hunting him for murder, while he tries to stop Professor Jordan (Godfrey Tearle) from sending secrets out of the country. Hannay is assisted by Pamela (Madeleine Carroll), an unwilling accomplice who discovers the truth.', '1935', '39steps.jpg', 'skPWOPTjsv8', 741);

--
-- Indeksy dla zrzutów tabel
--

--
-- Indexes for table `content`
--
ALTER TABLE `content`
 ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT dla tabeli `content`
--
ALTER TABLE `content`
MODIFY `id` int(11) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=42;