<div id="home">
<h1>Linkin Park</h1><br>
<p>
WE ARE NOT SATISFIED. WE ARE HUNGRY.
HUNGRY FOR THE VISCERAL. CATHARTIC. INSPIRED.
DEFIANT. WE ARE NOT HEROES OR ANTI-HEROES.
WE CARRY ONLY THE FLAG THAT IS OUR OWN.
NOW IS NOT THE TIME TO LOOK BACK TO SEE IF
ANYONE IS FOLLOWING.
NOW IS THE TIME TO CHARGE FORWARD INTO THE UNKNOWN.
</p>
</div>